language: node_js
node_js: lts/*
before_script:
  - "./bin/deploy.sh"
after_success:
  - "npm run push:coveralls"
jobs:
  include:
    - stage: test
      script: "npm run test:lint"
  allow_failures:
    - stage: test
      script: "npm run test:security"
notifications:
  email:
    recipients: dipustovit@gmail.com
    on_success: change
    on_failure: always